[build]
base = "wedding-site"
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
VITE_SUPABASE_URL = "https://oewyfxlphemxgslyxmbe.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ld3lmeGxwaGVteGdzbHl4bWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNDI4NDcsImV4cCI6MjA4MTkxODg0N30.Qzx4Pvc7qcg3NHMNZv93Rcb2GSpbrEPRd_ueiT3ZSbE"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200